services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9091:9090"  # Prometheus estará accesible en el puerto 9091
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Asegúrate de que el archivo de configuración de Prometheus esté montado
    networks:
      - smart_my-net

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - smart_my-net

networks:
  smart_my-net:
    driver: bridge